---
version: '3.7'
services:
  app:
    image: darylwalsh/phoenix:1.4.10
    build: .
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - RELX_REPLACE_OS_VARS=true
    ports:
      - '4000:4000'
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    image: postgres:10
    ports:
      - '5432:5432'
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
