apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactolatry-deployment
  labels:
    app: reactolatry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactolatry
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 34%
      maxUnavailable: 34%
  template:
    metadata:
      name: reactolatry
      labels:
        app: reactolatry
    spec:
      containers:
        - name: reactolatry
          image: darylwalsh/reactolatrydev:0.1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: REACT_APP_HTTP_ENDPOINT
              value: http://reactolatry:4000/api
            - name: REACT_APP_WS_ENDPOINT
              value: ws://reactolatry:4000/socket
          resources: {}
          securityContext:
            privileged: false
            procMount: Default
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
